server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false

spring:
  application:
    name: auth_service

  datasource:
    url: jdbc:mysql://localhost:3306/bus_application?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: rajgaming688@gmail.com
    password: wjtl gdtw wkuv hdqo
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  secret: BusApp_JWT_Secret_2026_StrongKey_9fA7xL2PqR8MZK
  expiration: 86400000

kafka:
  bootstrap-servers: localhost:9092

  topic:
    request:
      traveller-create: traveller-create-topic
    response:
      traveller-update: traveller-update-topic

  group:
    traveller-update: traveller-update-group

  consumer:
    max-attempts: 3
    retry-interval: 1000

  listener:
    concurrency: 3